### ISSUE TITLE
Google "trunk" Fonts don't exist

### ISSUE THREAD

**Issue by srs1978** [caskroom/homebrew-fonts#1015]
#### General troubleshooting steps

- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

All of the various fonts that are using a path like: https://github.com/google/fonts/trunk do not work because there's no "trunk" in the repo any more.  Example one is inconsolata (but there's like 186 in total using that path.)

#### Output of your command with `--verbose --debug`

```
N/A
```

#### Output of `brew cask doctor`

```
N/A
```

**Comment by eubenesa** [comment]
+1

`$ brew cask install font-roboto-mono
==> Checking out https://github.com/google/fonts/trunk/apache/robotomono
Error: Download failed on Cask 'font-roboto-mono' with message: Command failed to execute!

==> Failed command:
/usr/bin/svn checkout --force --config-option config:miscellany:use-commit-times=yes --trust-server-cert --non-interactive https://github.com/google/fonts/trunk/apache/robotomono #<Pathname:/Users/esa/Library/Caches/Homebrew/Cask/font-roboto-mono--svn>

==> Standard Output of failed command:


==> Standard Error of failed command:
svn: E170013: Unable to connect to a repository at URL 'https://github.com/google/fonts/trunk/apache/robotomono'
svn: E175002: Unexpected HTTP status 504 'Gateway Timeout' on '/google/fonts/trunk/apache/robotomono'


==> Exit status of failed command:
#<Process::Status: pid 15351 exit 1>
Error: nothing to install`

**Comment by vitorgalvao** [comment]
To be honest, this is one of those cases where we either get the PRs to fix them, or we remove them.

Reason being it’s likely many of those aren’t used, and the maintainer time isn’t worth it.

**Comment by srs1978** [comment]
I'll come up with a commit this evening, it's just a simple sed fix.  There's actually a few other fonts using the same repo, but they are using the /raw/ access path.  


I think most of them are still valid, they just got rid of the SVN trunk tag. I'm actually not 100% sure if that's a Github thing or something Google's font team did.

Is there some preference for using SVN?

**Comment by vitorgalvao** [comment]
No preference. SVN was used out of necessity. We even removed support once, but forgot about the fonts and broke them, so had to add it back.

**Comment by sscotth** [comment]
What this a temporary problem?

```sh
$ brew cask install font-roboto-mono
==> Checking out https://github.com/google/fonts/trunk/apache/robotomono
==> No checksum defined for Cask font-roboto-mono, skipping verification
==> Installing Cask font-roboto-mono
==> Moving Font 'RobotoMono-Bold.ttf' to '/Users/scott/Library/Fonts/RobotoMono-
==> Moving Font 'RobotoMono-BoldItalic.ttf' to '/Users/scott/Library/Fonts/Robot
==> Moving Font 'RobotoMono-Italic.ttf' to '/Users/scott/Library/Fonts/RobotoMon
==> Moving Font 'RobotoMono-Light.ttf' to '/Users/scott/Library/Fonts/RobotoMono
==> Moving Font 'RobotoMono-LightItalic.ttf' to '/Users/scott/Library/Fonts/Robo
==> Moving Font 'RobotoMono-Medium.ttf' to '/Users/scott/Library/Fonts/RobotoMon
==> Moving Font 'RobotoMono-MediumItalic.ttf' to '/Users/scott/Library/Fonts/Rob
==> Moving Font 'RobotoMono-Regular.ttf' to '/Users/scott/Library/Fonts/RobotoMo
==> Moving Font 'RobotoMono-Thin.ttf' to '/Users/scott/Library/Fonts/RobotoMono-
==> Moving Font 'RobotoMono-ThinItalic.ttf' to '/Users/scott/Library/Fonts/Robot
🍺  font-roboto-mono was successfully installed!
```

**Comment by vitorgalvao** [comment]
It indeed looks like this is now working.

That said, I’d still take the change. Still planning on doing it, @srs1978?

**Comment by miccal** [comment]
Closing due to lack of response.
