### ISSUE TITLE
Outdated casks with nerd-fonts

### ISSUE THREAD

**Issue by mashehu** [caskroom/homebrew-fonts#1222]
#### Description of issue
Nerd-fonts were recently updated to v1.1.0. 
I updated the firacode versions. But afterwards I thought that maybe there is a better way how to update all the different nerd-font casks all at once. If so I would gladly help there.

**Comment by vitorgalvao** [comment]
[Using `cask-repair`](https://github.com/caskroom/homebrew-cask/blob/aaf918df65103802962bb2a4075d414843d03b87/CONTRIBUTING.md#updating-a-cask):

```bash
for cask in $(brew --prefix)/Homebrew/Library/Taps/caskroom/homebrew-fonts/Casks/*nerd-font.rb; do
  cask-repair --cask-version 1.1.0 --blind-submit "$(basename "${cask}")"
done
```

Doing them all now. Thank you for the report.
