### ISSUE TITLE
The Ultimate Oldschool PC Font Pack

### ISSUE THREAD

**Issue by nrlquaker** [caskroom/homebrew-fonts#1311]
Is it ok to add [these fonts](http://int10h.org/oldschool-pc-fonts/readme/#about)?
I'm curious because its font pack. You can't download them separately.

**Comment by commitay** [comment]
I don't think we have any objections to font packs, easier to have them all in one Cask.

If you're not already using it, [font_casker](https://github.com/caskroom/homebrew-fonts/blob/master/CONTRIBUTING.md#automatic-generation) would be useful with this one as it looks like the pack has approx 100 fonts.

**Comment by nrlquaker** [comment]
Thanks for mentioning font_casker.
