### ISSUE TITLE
version policy for commit hash in url?

### ISSUE THREAD

**Issue by tomjonandy** [caskroom/homebrew-fonts#1345]
I'm looking at adding some fonts from [The League of Moveable Type](https://www.theleagueofmoveabletype.com), but the eventual download url (after following redirects) is only versioned in that it has the git commit hash (sometimes full, sometimes short) in it. I can see a few of options:
 - put the commit hash as the version, this is what has already been done for font-league-spartan (I don't really like this, not least because a full commit hash as a version seems very OTT)
 - use the original, unversioned download url (as in, before redirects) as unversioned (put `version :latest`)
 - use the versioned download url but treat it as if it wasn't (put `version :latest`)

Please let me know your thoughts regarding this.

**Comment by commitay** [comment]
Looks like they are hosted on GitHub so you can do something like this:
https://github.com/caskroom/homebrew-fonts/blob/c424060fc897c91eebdd4b8690f543381ffec555/Casks/font-xkcd.rb#L1-L10

**Comment by tomjonandy** [comment]
What about e.g. [Junction](https://www.theleagueofmoveabletype.com/junction) ([GitHub](https://github.com/theleagueof/junction)) which has regular, light and bold variants, given you can only have one url (*I think*)

**Comment by commitay** [comment]
You can use the zip archive of master.

https://github.com/caskroom/homebrew-fonts/blob/cb406b6bd3096ad5c16e4e1c1edcc3badf75a4a5/Casks/font-space-mono.rb#L1-L13

**Comment by tomjonandy** [comment]
Thank you, I didn't realise you could do that!
