### ISSUE TITLE
Missing Nerd Fonts

### ISSUE THREAD

**Issue by resech** [caskroom/homebrew-fonts#1437]
Hello,

It looks like the fonts added in releases 1.1.0 and 1.2.0 haven't been added to the cask. The following don't have formulas:

Arimo
Cousine
Go-Mono
InconsolataGo
InconsolataLGC
Tinos
Ubuntu

**Comment by vitorgalvao** [comment]
> formulas

Casks. They have different names because they are built differently and behave differently.

We’ll accept PRs for the missing fonts, if you care to submit them.
