### ISSUE TITLE
New nerd font iosevka version

### ISSUE THREAD

**Issue by pencilcheck** [caskroom/homebrew-fonts#1522]
#### General troubleshooting steps

https://github.com/ryanoasis/nerd-fonts/issues/229

- [ ] I have retried my command with `--force` and the issue is still present.
- [ ] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [ ] None of the templates was appropriate for my issue, or I’m not sure.
- [ ] I ran `brew update-reset && brew update` and retried my command.
- [ ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [ ] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

{{replace this}}

#### Output of your command with `--verbose --debug`

```
{{replace this}}
```

#### Output of `brew cask doctor`

```
{{replace this}}
```

**Comment by pencilcheck** [comment]
Cool, thanks if this is being updated, that would be awesome.

**Comment by commitay** [comment]
@pencilcheck All nerd fonts are at the current released version `1.2.0`

Upstream hasn't released a newer version so there is nothing to update.

Feel free to submit PRs when upstream does a new release. 
https://github.com/ryanoasis/nerd-fonts/releases

**Comment by pencilcheck** [comment]
Ah, that sucks. But appreciate for the response.

**Comment by pencilcheck** [comment]
@commitay looks like a new release has been pushed: https://github.com/ryanoasis/nerd-fonts/releases that includes the latest changes.

**Comment by commitay** [comment]
We did update to `2.0.0` briefly but had to revert.

See https://github.com/caskroom/homebrew-fonts/pull/1620

**Comment by pencilcheck** [comment]
Oh that sucks.

**Comment by ryanoasis** [comment]
Yeah sorry about this. We'll rebuild them soon. Probably this week. Pulled them after reports of some serious issues
