### ISSUE TITLE
Request: remaining fonts from George Douros

### ISSUE THREAD

**Issue by rolandwalker** [caskroom/homebrew-fonts#161]
http://users.teilar.gr/~g1951d/Nilus.zip
http://users.teilar.gr/~g1951d/Gardiner.zip
http://users.teilar.gr/~g1951d/Anatolian.zip
http://users.teilar.gr/~g1951d/Maya.zip

**Comment by adityadalal924** [comment]
Issue is N/A as per https://github.com/caskroom/homebrew-fonts/pull/373 - the fonts were taken down

**Comment by vitorgalvao** [comment]
Care to be the one to close it, @adityadalal924?
