### ISSUE TITLE
Sintony font is failing

### ISSUE THREAD

**Issue by RobertoGongora** [caskroom/homebrew-fonts#296]
brew cask install font-sintony
==> Checking out https://github.com/w0ng/googlefontdirectory/trunk/fonts/sintony
Error: Download failed on Cask 'font-sintony' with message: Command failed to execute!

==> Failed command:
["/usr/bin/svn", "checkout", "--force", "--config-option", "config:miscellany:use-commit-times=yes", "--trust-server-cert", "--non-interactive", "https://github.com/w0ng/googlefontdirectory/trunk/fonts/sintony", "#<Pathname:/Library/Caches/Homebrew/font-sintony--svn>", "-r", "50"]

==> Output of failed command:

==> Exit status of failed command:
#<Process::Status: pid 66832 exit 69>

This is due the https://github.com/w0ng/googlefontdirectory/trunk/fonts/sintony giving a 404 error

**Comment by rolandwalker** [comment]
Hi!

I can't duplicate this error.  (`svn` is using the URL differently than the browser does.)

The "#" for the exit status is very suspicious though.  That should be a number.  Have you upgraded to the latest version of Homebrew-cask:
```bash
$ brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup
```
?

**Comment by RobertoGongora** [comment]
Thanks for the quick response!

I honestly don't know what happened, but I just tried to duplicate the issue to take a screenshot, but... it just worked. I literally didn't do anything, so ... I'm a bit confused.

Anyway, seems like everything is working, the fonts are installed and it's all good! I'll keep an eye on it and report back on any further issues I might have :smile:
