### ISSUE TITLE
Can't install a font

### ISSUE THREAD

**Issue by spencerlyon2** [caskroom/homebrew-fonts#307]
Am I doing something wrong here?:

```bash
~|⇒ brew tap caskroom/fonts
Warning: Already tapped!
~|⇒ brew update
Already up-to-date.
~|⇒ brew cask install font-charis-sil
Error: No available Cask for font-charis-sil
Error: nothing to install
```

I [think](https://github.com/caskroom/homebrew-fonts/blob/master/Casks/font-charis-sil.rb) this cask exists, but maybe by a different name?

**Comment by ndr-qef** [comment]
I am quite sorry for the late reply.

I am unable to reproduce, but the fact that `font-charis-sil` is not found suggests that the issue may stem from your local tap. Could you try untapping and re-tapping caskroom/fonts?

**Comment by EvanHahn** [comment]
FWIW, I'm having a similar issue. I tried untapping and re-tapping but still failed.

**Comment by vitorgalvao** [comment]
If this is still an issue, please open a new one, and [follow the procedure](https://github.com/caskroom/homebrew-cask#reporting-bugs).
