### ISSUE TITLE
Unable to install fonts from Google Fonts

### ISSUE THREAD

**Issue by Reefki** [caskroom/homebrew-fonts#308]
I'm no longer able to install font from Google fonts directory, here is the output:
```
$ brew cask install font-montserrat
==> Checking out https://github.com/w0ng/googlefontdirectory/trunk/fonts/montserrat
Error: Download failed on Cask 'font-montserrat' with message: Command failed to execute!

==> Failed command:
["/usr/bin/svn", "checkout", "--force", "--config-option", "config:miscellany:use-commit-times=yes", "--trust-server-cert", "--non-interactive", "https://github.com/w0ng/googlefontdirectory/trunk/fonts/montserrat", "#<Pathname:/Library/Caches/Homebrew/font-montserrat--svn>", "-r", "50"]
```

When I checked the repository: https://github.com/w0ng/googlefontdirectory, it seems has been abandoned.

**Comment by ndr-qef** [comment]
Indeed, the binary files for Google Fonts have been migrated to an official GitHub repository.

We will work out a transition, which will hopefully amount to a simple url substitution. It may take some time, unfortunately.

**Comment by ndr-qef** [comment]
Google Fonts should work again now. Let me know if there are any problems.
