### ISSUE TITLE
Raleway error

### ISSUE THREAD

**Issue by CathyMacars** [caskroom/homebrew-fonts#320]
brew cask instal font-raleway
==> Checking out https://github.com/google/fonts/trunk/ofl/raleway
==> Hardlinking Font 'Raleway-Bold.ttf' to '/Users/Catarina/Library/Fonts/Raleway-Bold.ttf'
==> Hardlinking Font 'Raleway-ExtraBold.ttf' to '/Users/Catarina/Library/Fonts/Raleway-ExtraBold.ttf'
==> Hardlinking Font 'Raleway-ExtraLight.ttf' to '/Users/Catarina/Library/Fonts/Raleway-ExtraLight.ttf'
**Error: It seems the hardlink source is not there: '/opt/homebrew-cask/Caskroom/font-raleway/latest/Raleway-Heavy.ttf'**

**Comment by ndr-qef** [comment]
Raleway has been updated to version 3.000 in the Google Fonts directory, removing a weight that was included in our cask. The problem was fixed in b5f46b3.

Thanks for the report.
