### ISSUE TITLE
Lato download returns 403

### ISSUE THREAD

**Issue by rockymadden** [caskroom/homebrew-fonts#324]
`curl: (22) The requested URL returned error: 403 Forbidden`

If you hit the URL via the browser it does work, but it does a bit of redirection:

![redirection](http://share.rockymadden.com/image/3W400h223q1D/Image%202015-05-15%20at%2012%3A21%3A17.png)

**Comment by ndr-qef** [comment]
From my machine, `font-lato` downloads normally. Can you still reproduce the issue? If so, do you have a custom .curlrc?

**Comment by rockymadden** [comment]
Oddly enough, it does work today. I know it had been broken for quite some time on multiple computers on multiple networks (I only tried again and reported yesterday). I do not have a custom .curlrc, but a good thought for sure. Since this cannot be reproduced, I will close. Thanks for taking a look!
