### ISSUE TITLE
font-montserrat

### ISSUE THREAD

**Issue by RobertoGongora** [caskroom/homebrew-fonts#340]
There's some errors when installing the Montserrat font. Screenshot below:
![shell](https://cloud.githubusercontent.com/assets/1845147/8072156/b438a2d0-0ed7-11e5-9f7c-4e0c1a026c86.png)

But when I untar the file and open the folder, I see this:
![font-montserrat--svn-latest](https://cloud.githubusercontent.com/assets/1845147/8072160/c6921754-0ed7-11e5-84cb-b17bcaa8dc69.png)

Clearly, the "Hairline" variation is missing and that's probably what's causing the error, but it's weird that the rest of the fonts aren't being linked.

Anyway, my two cents :)

**Comment by ndr-qef** [comment]
The Hairline weight has been removed from the font. The cask was fixed in d1e56f4.

The reason no font is being linked is that there is no partial failure mode for `brew cask install`; when commands fail, it is generally desirable not to leave a trail of files.
