### ISSUE TITLE
Please add menlo

### ISSUE THREAD

**Issue by jsergur** [caskroom/homebrew-fonts#347]
Please add the menlo font it's popular for programming.

**Comment by jimbojsb** [comment]
Isn't this font shipped on Macs by default?

**Comment by jsergur** [comment]
Yes.

**Comment by jsergur** [comment]
but I delete it

**Comment by jsergur** [comment]
and want to reinstall

**Comment by jsergur** [comment]
thus I need

**Comment by jsergur** [comment]
homebrew-fonts

**Comment by jimbojsb** [comment]
I don't think Menlo is open source and I don't see a place we can download it or check the license on. It looks like we do have Meslo which is a modified alternative. If you deleted it and want to re-add it, it'd be much easier to just grab it from another Mac.

**Comment by vitorgalvao** [comment]
Agreed. Closing.

Also @jsergur, please don’t post a sentence broken down as posts.
