### ISSUE TITLE
Font Overview

### ISSUE THREAD

**Issue by antares2001** [caskroom/homebrew-fonts#379]
Hello!

Thanks a lot for your great and large font cask. It's amazing!

However, as it's so big and hard to oversee, what about an auto-generated PDF for the fonts contained in the cask? Would it be possible to add that to the main directory? This would be a huge help. I'm unfortunately not skilled enough to contribute it myself.

Nevertheless I want to thank you guys for your work!

**Comment by vitorgalvao** [comment]
No, [we don’t intend to become a discoverability service](https://github.com/caskroom/homebrew-cask/issues/4323#issuecomment-67257513). This has been [discussed and refused multiple times](https://github.com/caskroom/homebrew-cask/issues/5425#issuecomment-49512837), as [it is not part of the goals of homebrew-cask](https://github.com/caskroom/homebrew-cask/issues/3817#issuecomment-39868330). Amongst other things, the logistics are unsustainable.

Having a preview of fonts would fall under that category.
