### ISSUE TITLE
Force Push

### ISSUE THREAD

**Issue by jrtc27** [caskroom/homebrew-fonts#392]
A force push was made within the last few days, causing fast-forward merges to fail and homebrew to not be able to update this tap. The difference appears to be that @victorpopkov's email address was changed from `Ngrd@users.noreply.github.com` in all of his commits. As a user of this repository, this was an unnecessary inconvenience.

**Comment by victorpopkov** [comment]
Yes, I apologize for all the inconvenience caused by this action. I know that this an awful practice and you should avoid that at all costs, but there are moments in life where you have to make difficult decisions. :bow:

**Comment by jrtc27** [comment]
I realise sometimes situations like this can occur, so as long as force pushes are reserved for exceptional circumstances, then it's fine.

**Comment by jawshooah** [comment]
@vitorgalvao What do you think about making `master` a [protected branch](https://help.github.com/articles/about-protected-branches/) on all repos to prevent something like this from happening again?

**Comment by victorpopkov** [comment]
I also agree. It should be protected from force pushing.

**Comment by vitorgalvao** [comment]
Agreed here as well.

**Comment by vitorgalvao** [comment]
Doing it now.
