### ISSUE TITLE
Error: Command failed to execute!

### ISSUE THREAD

**Issue by tristan-k** [caskroom/homebrew-fonts#401]
$ brew cask install font-libertine
     ==> Downloading https://github.com/khaledhosny/libertine/archive/master.tar.gz
     ######################################################################## 100.0%
     ==> Hardlinking Font 'libertinekeyboard-regular.otf' to '/Users/tristank/Library/Fonts/libertinekeyboard-regular.otf'
     ==> ln: /Users/tristank/Library/Fonts/libertinekeyboard-regular.otf: Cross-device link
     Error: Command failed to execute!
     
     ==> Failed command:
     ["/bin/ln", "-hf", "--", "#<Pathname:/opt/homebrew-cask/Caskroom/font-libertine/latest/libertine-master/libertinekeyboard-regular.otf>", "#<Pathname:/Users/tristank/Library/Fonts/libertinekeyboard-regular.otf>"]

     ==> Output of failed command:
     
     
     ==> Exit status of failed command:
     #<Process::Status: pid 6665 exit 1

**Comment by tristan-k** [comment]
I cant install a single font. It's not related to a specific font.

**Comment by vitorgalvao** [comment]
You should’ve been more specific, we can’t guess that.

Please [follow this guide](https://github.com/caskroom/homebrew-cask#reporting-bugs) and report back only if you still have an issue.

**Comment by tristan-k** [comment]
I'm sorry. I didnt meant to be unspecific. The issue still remains. What else information can I provide?

```
$ brew doctor --verbose
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Your Xcode (7.0.1) is outdated
Please update to Xcode 7.1.
Xcode can be updated from the App Store.
```

```
$ brew cask install --verbose font-sauce-code-powerline                                                                                                                                                                              
Already downloaded: /Library/Caches/Homebrew/font-sauce-code-powerline--svn-latest.tar
==> Hardlinking Font 'Sauce Code Powerline Black.otf' to '/Users/tristank/Library/Fonts/Sauce Code Powerline Black.otf'
==> ln: /Users/tristank/Library/Fonts/Sauce Code Powerline Black.otf: Cross-device link
Error: Command failed to execute!

==> Failed command:
["/bin/ln", "-hf", "--", "#<Pathname:/opt/homebrew-cask/Caskroom/font-sauce-code-powerline/latest/Sauce Code Powerline Black.otf>", "#<Pathname:/Users/tristank/Library/Fonts/Sauce Code Powerline Black.otf>"]

==> Output of failed command:


==> Exit status of failed command:
#<Process::Status: pid 50890 exit 1>
```

**Comment by vitorgalvao** [comment]
Have you run `brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup`?

And please update your Xcode, like the warning says.

**Comment by vitorgalvao** [comment]
Have you run `brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup`? You also did not run `brew cask doctor`. You need to do all the steps.

And please update your Xcode, like the warning says.

**Comment by tristan-k** [comment]
I'm clueless. Could be related to openzfs? I'm using a filevault2 encrypted home partition with openzfs.

```
$ brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup
Already up-to-date.
```

**Comment by vitorgalvao** [comment]
Again, **you haven’t given the results of `brew cask doctor`**.

**Comment by tristan-k** [comment]
Still updating xcode to 7.1. Will post the results when it's ready.
