### ISSUE TITLE
Fira code only installed FiraCode-Regular

### ISSUE THREAD

**Issue by dstroot** [caskroom/homebrew-fonts#422]
Retina, medium, etc NOT installed.

**Comment by vitorgalvao** [comment]
What’s the result of `brew cask cat font-fira-code`?

**Comment by dstroot** [comment]
❯ brew cask cat font-fira-code
cask :v1 => 'font-fira-code' do
  version '0.6'
  sha256 '0ae8324527fbcbaf93eaf7be1171b5fa039b8444154a7262a914f75c6da78aae'

  url 'https://github.com/tonsky/FiraCode/releases/download/0.6/FiraCode-Regular.otf'
  homepage 'https://github.com/tonsky/FiraCode'
  license :ofl

  font 'FiraCode-Regular.otf'
end

~
❯

**Comment by dstroot** [comment]
❯ brew cask install font-fira-code --force
==> Downloading https://github.com/tonsky/FiraCode/releases/download/0.6/FiraCode-Regular.otf
Already downloaded: /Library/Caches/Homebrew/font-fira-code-0.6.otf
==> It seems there is already a Font at '/Users/Dan/Library/Fonts/FiraCode-Regular.otf'; not linking
🍺  font-fira-code staged at '/opt/homebrew-cask/Caskroom/font-fira-code/0.6' (132K)

~
❯

**Comment by vitorgalvao** [comment]
As suspected, you don’t have the latest cask. You need to `brew update`.

**Comment by dstroot** [comment]
doing that now - thanks

**Comment by dstroot** [comment]
Boom!
---
```
❯ brew cask cat font-fira-code
cask :v1 => 'font-fira-code' do
  version '1.101'
  sha256 'bbe851dcd681506dc44e86c425f917614016b43ad5f22de7b9d2afe819997271'

  url "https://github.com/tonsky/FiraCode/releases/download/#{version}/FiraCode_#{version}.zip"
  homepage 'https://github.com/tonsky/FiraCode'
  license :ofl

  font 'FiraCode-Bold.otf'
  font 'FiraCode-Light.otf'
  font 'FiraCode-Medium.otf'
  font 'FiraCode-Regular.otf'
  font 'FiraCode-Retina.otf'
end

~
❯
```

**Comment by dstroot** [comment]
If I can't figure this out I may have to open another issue.  I have tried uninstall and reinstalling as well as installing with --force:

```
❯ brew cask install font-fira-code --force
==> Downloading https://github.com/tonsky/FiraCode/releases/download/1.101/FiraCode_1.101.zip
######################################################################## 100.0%
==> Verifying checksum for Cask font-fira-code
Error: It seems the hardlink source is not there: '/opt/homebrew-cask/Caskroom/font-fira-code/1.101/FiraCode-Bold.otf'

~
❯
```

**Comment by vitorgalvao** [comment]
`brew cask uninstall --force font-fira-code && brew cleanup --force && brew cask cleanup && rm -rf "$(brew --cache)" && brew update && brew install font-fira-code`

**Comment by dstroot** [comment]
Thanks for the help!  Needed "cask" in last stmt.
