### ISSUE TITLE
Hardlink source absent error

### ISSUE THREAD

**Issue by contraultra** [caskroom/homebrew-fonts#429]
I am trying to create a cask for a font. Although it passed `audit`, it had this error:

```
Homebrew $ brew cask install font-overpass
==> Downloading https://github.com/RedHatBrand/overpass/releases/download/2.1/ov
######################################################################## 100.0%
==> Verifying checksum for Cask font-overpass
Error: It seems the hardlink source is not there: '/opt/homebrew-cask/Caskroom/font-overpass/2.1/Overpass-Bold-Italic.ttf'
```

Any thoughts?

p.s. on https://github.com/caskroom/homebrew-fonts/blob/master/README.md, build is failing

**Comment by adityadalal924** [comment]
SVN removed - we need to revert it until a better fix is found.
https://github.com/caskroom/homebrew-cask/pull/16215

**Comment by contraultra** [comment]
In light of this, can I(and others) still submit a pull request for a font submission or wait it out?

**Comment by adityadalal924** [comment]
You can submit a PR - we'll likely hold it until the issue is fixed, however. If you have any thoughts on a better solution (we really don't want to use SVN in the long-term), please add to the discussion at https://github.com/caskroom/homebrew-cask/pull/16215

**Comment by contraultra** [comment]
so the merged pull request #430 still presents the error above and you mentioned there that it's not dependent on svn... reopen this issue?

**Comment by adityadalal924** [comment]
Found the issue:

Needs to be of the form:

`font "overpass-fonts-ttf-#{version}/Overpass-Bold.ttf"`, etc.

PR incoming

**Comment by adityadalal924** [comment]
Not at a computer at the moment, feel free to open a PR with the fix
