### ISSUE TITLE
Error on installing font-nanumgothiccoding

### ISSUE THREAD

**Issue by openingnow** [caskroom/homebrew-fonts#432]
While running `brew cask install font-nanumgothiccoding`, I faced error: 
```
Error: Download failed on Cask 'font-nanumgothiccoding' with message:
Download failed: https://github.com/google/fonts/trunk/ofl/nanumgothiccoding
```
I found https://github.com/google/fonts/tree/master/ofl/nanumgothiccoding is the new url.
I'm not sure if just editing nanumgothiccoding.rb is fine, so I leave as issue, not PR.

**Comment by vitorgalvao** [comment]
The url is correct (it’s so it can be installed via Subversion, technical reasons).

Just tested it and it works. Please `brew update` and try again.

**Comment by openingnow** [comment]
Succeeded without error. It's wierd;

Anyway, thanks.
