### ISSUE TITLE
Fonts missing 'name'

### ISSUE THREAD

**Issue by vitorgalvao** [caskroom/homebrew-fonts#437]
All these fonts are missing the (mandatory) `name` stanza. They should be outright deleted from this list as they are fixed. List should be rebuilt periodically (to make sure everything is up to date).

To rebuild the list (it assumes you’re inside `homebrew-fonts/Casks`):

```bash
for font in $(grep --files-without-match --extended-regexp "\s+name '.*'" *); do
  echo "+ [${font}](../blob/master/Casks/${font})"
done | pbcopy
```

+ [font-bm-hanna.rb](../blob/master/Casks/font-bm-hanna.rb)
+ [font-clara.rb](../blob/master/Casks/font-clara.rb)
+ [font-lao-muang-don.rb](../blob/master/Casks/font-lao-muang-don.rb)
+ [font-lao-muang-khong.rb](../blob/master/Casks/font-lao-muang-khong.rb)
+ [font-lao-sans-pro.rb](../blob/master/Casks/font-lao-sans-pro.rb)
+ [font-lateef.rb](../blob/master/Casks/font-lateef.rb)
+ [font-miama.rb](../blob/master/Casks/font-miama.rb)
+ [font-monoone.rb](../blob/master/Casks/font-monoone.rb)
+ [font-nanum-brush-script.rb](../blob/master/Casks/font-nanum-brush-script.rb)
+ [font-nanum-pen.rb](../blob/master/Casks/font-nanum-pen.rb)
+ [font-souliyo-unicode.rb](../blob/master/Casks/font-souliyo-unicode.rb)
+ [font-tharlon.rb](../blob/master/Casks/font-tharlon.rb)

**Comment by caarlos0** [comment]
@vitorgalvao PR #439 might fix this issue...

**Comment by vitorgalvao** [comment]
Done. All remaining fonts are from https://github.com/caskroom/homebrew-fonts/issues/445.
