### ISSUE TITLE
Disable wiki

### ISSUE THREAD

**Issue by adidalal** [caskroom/homebrew-fonts#469]
(Title)

same needs to be done for a few other caskroom repos also

**Comment by vitorgalvao** [comment]
Seems like it isn’t necessary.

What I see logged in:
![image](https://cloud.githubusercontent.com/assets/1699443/12848334/26cc98fa-cc11-11e5-9e2f-6f7bba2b2cb8.png)

What I see logged out:
![image](https://cloud.githubusercontent.com/assets/1699443/12848351/40a70d8c-cc11-11e5-885b-96acc2078917.png)
