### ISSUE TITLE
font source-han-sans could be installed from a SuperOTC file

### ISSUE THREAD

**Issue by fyears** [caskroom/homebrew-fonts#519]
Currently, the [cask](https://github.com/caskroom/homebrew-fonts/blob/master/Casks/font-source-han-sans.rb) downloads a VERY large zip file containing duplicating fonts in different formats.

A better way is just downloading a MUCH smaller [SuperOTC](https://github.com/adobe-fonts/source-han-sans/raw/release/SuperOTC/SourceHanSans.ttc.zip) file, and installing it.

(But I am finding troubles editing the cask on my computer, so I post an issue here, and hopefully someone could edit the cask to close this issue.)

**Comment by vitorgalvao** [comment]
> But I am finding troubles editing the cask on my computer

Why?

Can you paste here the resulting cask?

**Comment by vitorgalvao** [comment]
Closing for lack of reply.
