### ISSUE TITLE
Draft naming spec and rename 

### ISSUE THREAD

**Issue by alerque** [caskroom/homebrew-fonts#521]
Per the discussion that started in #515, I think the old seat-of-the-pants naming was working out better that the letter-of-the-law names without hyphens recently kludged in from the cask naming standards.

I propose _not_ pretending font file names are the same as Mac app names "as found on disk" and using the font face name as specified by the font itself instead.

- [x] Document how font casks should be named (documentation existed in CONTRIBUTING.md, it just needed tweaking)
- [x] Rename existing font casks to match (recently renamed fonts that don't comply reverted, others to be reset on an as-spotted bases)

**Comment by vitorgalvao** [comment]
Just to be clear we’re on the same page, the invitation was for you to make the first draft of said rules, in a document similar to the [token reference](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md). Something real we can start discussing.

**Comment by alerque** [comment]
@vitorgalvao I'm putting together a PR now, but you're behind your own project. You guys actually already _have_ this documentation, it just needed minor tweaks.

**Comment by vitorgalvao** [comment]
You’re right, I completely forgot about that.
