### ISSUE TITLE
attempting to install font-input generates error

### ISSUE THREAD

**Issue by ex-nerd** [caskroom/homebrew-fonts#552]
Something appears to be mis-configured with the cask definition:

```
# brew cask install font-input
Error: Cask 'font-input' definition is invalid: Bad header line: '{:v1=>"font-input"}' does not match file name
```

**Comment by vitorgalvao** [comment]
Please *always* follow the [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) guide.

As soon as you do, your issue will be solved.

**Comment by ex-nerd** [comment]
Thanks for the poke.  Apparently my homebrew git checkout got stuck in a weird merge conflict state and wasn't refreshing properly.  Things work properly now.
