### ISSUE TITLE
404 on FontAwesome

### ISSUE THREAD

**Issue by richarddewit** [caskroom/homebrew-fonts#573]
```
$ brew cask install font-fontawesome
==> Downloading https://fortawesome.github.io/Font-Awesome/assets/font-awesome-4.6.1.zip

curl: (22) The requested URL returned error: 404 Not Found
Error: Download failed on Cask 'font-fontawesome' with message: Download failed: https://fortawesome.github.io/Font-Awesome/assets/font-awesome-4.6.1.zip
```

It seems that v4.6.1 no longer exists. Please upgrade to [v4.6.2](https://fortawesome.github.io/Font-Awesome/assets/font-awesome-4.6.2.zip)

**Comment by richarddewit** [comment]
Seems like they immediately delete their old archives.. v4.6.2 now also returns 404. 

New version [v4.6.3](http://fontawesome.io/assets/font-awesome-4.6.3.zip)

**Comment by vitorgalvao** [comment]
Contributing a new version is as simple as [running one command](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md).

**Comment by richarddewit** [comment]
Ah good to know, will do this soon™
