### ISSUE TITLE
Guidance needed to resolve font naming conflict/confusion

### ISSUE THREAD

**Issue by vsivsi** [caskroom/homebrew-fonts#611]
Hi, I'd like to create a *new* cask for an open font called "[Crimson Text](https://github.com/skosch/Crimson)". The observant reader will immediately think, "Hey isn't there already a cask for a font named [`crimson-text.rb`](https://github.com/caskroom/homebrew-fonts/blob/master/Casks/font-crimson-text.rb) in this repo?"  Why yes there is... but that's for a distinctly different (but closely related) typeface from the one I would like to add.

Huh?

The 30 second story here is that the creator of the "Crimson Text" typeface that I would like to add (and owner of the repo linked above, @skosch) is also the creator of the original "Crimson Text" font included in Google Fonts, which is the one currently pointed to by `crimson-text.rb`. [According to the creator](https://github.com/skosch/Crimson#naming-confusion), the font in Google Fonts is a very early version that Google repeatedly refused to update with the substantially redesigned newer typeface (which is intended to entirely supplant the "clumsy-looking" original). Essentially, the creator disavows the Google Fonts version, but seems powerless to replace/update it.

So, I'm asking for advice as to what to do here... I can:

1.  Replace the existing `crimson-text.rb` with the updated font (which is still *officially* called "Crimson Text" although according the creator, that usage has mostly fallen off to avoid confusion with the Google Fonts version).  Or...
2.  Create a new cask called `crimson.rb` for the updated font, and leave `crimson-text.rb` undisturbed (say, for historical reasons).  Or...
3.  Create a new cask called `crimson.rb` for the updated font, and remove the `crimson-text.rb` cask to avoid confusion.  Or...
4. ??? (something else I haven't considered) 

**1)** seems to comport most closely with my understanding of Crimson's creator's intent, but will lead to a visible change in the typeface for any users that upgrade the existing cask.
**2)** provides casks for both fonts, named according to their current most commonly used names, but does create the potential for ongoing confusion.
**3)** removes the potential for confusion, and seems the end state for 2) as well,  [once Google Code archives go away](https://github.com/caskroom/homebrew-fonts/issues/445), making the old version inaccessible (assuming nobody fixes it). 

Option **1)** would be my preference, assuming there are no objections; otherwise **2)** seems the least disruptive, although in that case, I'm not currently sure what would happen if someone installed both Casks on the same computer.

**Comment by skosch** [comment]
Well, since you've summoned me I may as well add that I see merit in all three of your options, and that I have no strong preference towards any one of them :)

One thing to consider may be that I have done zero cross-platform testing of the font. I'm on Linux, and things somehow always just worked for me, but it is possible that the Google has subjected their font offerings to some post-production tweaks I'm not privy to. At the same time, I've received plenty of bug requests over the years relating to vertical metrics problems and such, *some* of which have since been fixed by my amazing contributors, and then of course many of those fixes are likely missing from Google's version. (None of this is to mention the actual outlines, which have been entirely redrawn.)

I have no access to OS X, so all I can do is throw this out there for you guys to be mindful of.

**Comment by vitorgalvao** [comment]
Great report, @vsivsi, so detailed! Thank you also @skosch, for chiming in.

Option **1** all the way. You make a compelling argument for it, and it seems in the best interest of everyone. See you on the PR!

**Comment by vsivsi** [comment]
Great!  @skosch  I've been using Crimson on OS X for many months will no obvious issues. I even typeset my Ph.D. Thesis with it!  

![image](https://cloud.githubusercontent.com/assets/428642/16897863/be20453e-4b74-11e6-8c5f-51eabe4db058.png)

**Comment by vsivsi** [comment]
One more quick question for @vitorgalvao   The Crimson binary zip distribution file contains both `.ttf` and `.otf` files (which should be equivalent). Any preferences on which to symlink?

**Comment by vitorgalvao** [comment]
> Any preferences on which to symlink?

`.otf`.

**Comment by adidalal** [comment]
Just popping in here - the *easiest* method to have this cask update is if the current Crimson font was zipped up and published as a release via Github.

**Comment by skosch** [comment]
Could you elaborate? How would that work exactly?

**Comment by adidalal** [comment]
Whoops, may have misread the above - if there's already a binary zip distribution for the font would you mind pasting a link here? I can update the Cask from there

**Comment by skosch** [comment]
There isn't an up-to-date one, no. Can you pull the files directly from the repo?

**Comment by adidalal** [comment]
Don't believe that is currently possible, no. In that case, adding an up to date release would be the way to go. (Create a new release, upload the zip file of font faces in the files section)

**Comment by vsivsi** [comment]
Yes, I ran into this issue after resolving my questions above, and then got pulled onto other tasks without bottoming out on it.

**Comment by skosch** [comment]
So Crimson has a bunch of unresolved issues/bugs that I'd like to get sorted out first¹ before packaging any new releases on github, if that's cool?

¹with the help of my amazing *font-file-production-wizard* contributors on whose expertise I'm admittedly totally and utterly dependent, and without whose help we won't make any progress here, so cross your fingers :wink:
