### ISSUE TITLE
Guidance for upgrading fonts

### ISSUE THREAD

**Issue by swrobel** [caskroom/homebrew-fonts#624]
I realize that this is an issue with casks as a whole, although Mac apps typically auto-update and fonts do not. For fonts like [Hack](https://github.com/chrissimpkins/Hack/blob/master/CHANGELOG.md) that are actively developed and released, what is the recommended strategy for upgrading? I tried `brew cask install font-hack --force` but I got the following, which required me to manually delete the font from my library to get the new version to link:

```
==> It seems there is already a Font at '/Users/swrobel/Library/Fonts/Hack-Regular.otf'; not linking.
==> It seems there is already a Font at '/Users/swrobel/Library/Fonts/Hack-Italic.otf'; not linking.
==> It seems there is already a Font at '/Users/swrobel/Library/Fonts/Hack-Bold.otf'; not linking.
==> It seems there is already a Font at '/Users/swrobel/Library/Fonts/Hack-BoldItalic.otf'; not linking.
```

**Comment by jawshooah** [comment]
Seems like a bug, especially since installed fonts should be moved, not linked, per #13201. We must have missed that in the re-implementation of `install`. Will escalate to an issue on the core repo.

**Comment by jawshooah** [comment]
Closed in favor of https://github.com/caskroom/homebrew-cask/issues/23723
