### ISSUE TITLE
State of this repository? Or: Is the README up to date?

### ISSUE THREAD

**Issue by lunaryorn** [caskroom/homebrew-fonts#631]
This repository [appears to be very active](https://github.com/caskroom/homebrew-fonts/commits/master), font installation seems to be working well, people seem to be using it, but… the readme still says that it's [pre-release](https://github.com/caskroom/homebrew-fonts#pre-release), not even alpha, and refers to an [issue from 2014](https://github.com/caskroom/homebrew-fonts/issues/84).  The issue has been closed early this year though, without any further updates.

So what's the state of this repo now?  Is it alpha or not?  Can I safely use it?  Would you recommend me to use it?

**Comment by vitorgalvao** [comment]
Check the open issues. Two of them pertain to problems that affect the majority of casks. They won’t even pass `audit`.

Like all of homebrew-cask, this repo works fine and many people already depend on it, but at their own risk.
