### ISSUE TITLE
Question: Should I add Google fonts not listed in their website?

### ISSUE THREAD

**Issue by guerrero** [caskroom/homebrew-fonts#908]
As #906 reflects, there are some fonts that appear in the [Google fonts GitHub repo][1] but they don't appear in the [Google fonts website][1]. The fonts are the following:

- [Hanna][3]
- [Clara][4]
- [Miama][5]

I don't know if it would be helpful to add these fonts to this repo or in the other hand it would be a bad idea. So I wanted to get some advice in order to know how I should proceed.

Thanks!

[1]: https://github.com/google/fonts
[2]: https://fonts.google.com
[3]: https://github.com/google/fonts/tree/master/ofl/hanna
[4]: https://github.com/google/fonts/tree/master/ofl/clara
[5]: https://github.com/google/fonts/tree/master/ofl

**Comment by vitorgalvao** [comment]
Since these don’t have an homepage (i.e. a proper Google Fonts page), it would be better to not add them.
