### ISSUE TITLE
Patched fonts for Powerline users

### ISSUE THREAD

**Issue by nrlquaker** [caskroom/homebrew-fonts#953]
Is it ok to add [it](https://github.com/powerline/fonts)?

**Comment by miccal** [comment]
[I think they are already available](https://github.com/caskroom/homebrew-fonts/search?utf8=✓&q=powerline).

**Comment by vitorgalvao** [comment]
> [I think they are already available](https://github.com/caskroom/homebrew-fonts/search?utf8=✓&q=powerline).

Yep.
