### ISSUE TITLE
Font request: source-han-serif

### ISSUE THREAD

**Issue by xu-cheng** [caskroom/homebrew-fonts#968]
Name: Source Han Serif
Homepage: https://github.com/adobe-fonts/source-han-serif
URL:   https://raw.githubusercontent.com/adobe-fonts/source-han-serif/1.000R/SuperOTC/SourceHanSerif.ttc.zip and https://raw.githubusercontent.com/adobe-fonts/source-han-serif/1.000R/SuperOTC/SourceHanSerif.ttc.z01

I was intended to send a PR on my own. However, I have no idea how to make cask download two files for installation.

**Comment by vitorgalvao** [comment]
> I have no idea how to make cask download two files for installation.

You can’t. They need to be two casks. Why are the two files needed, though?

**Comment by xu-cheng** [comment]
Because it's a zip split into two parts.

**Comment by vitorgalvao** [comment]
Then unfortunately we cannot support it.

**Comment by tbsmcd** [comment]
@xu-cheng Hello.
My [pull request](https://github.com/caskroom/homebrew-fonts/pull/971) was merged. You can install these fonts.
